# .travis.yml for libpointing
#
# Authors: Izzatbek Mukhanov
# Copyright © Inria
# http://libpointing.org/
#
# This software may be used and distributed according to the terms of
# the GNU General Public License version 2 or any later version.
#

language: cpp

os:
    - linux
    - osx

before_install:
    - |
      if [ $TRAVIS_OS_NAME == linux ] ; then
          sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa ;
          sudo apt-get update -qq ;
      elif [ $TRAVIS_OS_NAME == osx ] ; then
          brew update ;
      fi

install:
    - |
      if [ $TRAVIS_OS_NAME == linux ] ; then
          sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev ; #qt5-default
          sudo apt-get install -qq qt5-default ;
          sudo apt-get install -qq libudev-dev ;
          sudo apt-get install -qq xorg-dev ;
          sudo apt-get install -qq freeglut3-dev ;
      elif [ $TRAVIS_OS_NAME == osx ] ; then
          brew ls | grep -wq qt || brew install qt ;
      fi

before_script:
    - qmake

script:
    - make